/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Lucas
 */
public class TelaBuscaEstatisticas extends javax.swing.JFrame {

    /**
     * Creates new form TelaBuscaEstatisticas
     */
    public TelaBuscaEstatisticas() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        boxMesMateria = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAnoMateria = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAnoMes = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnEstatisticaMesTabela = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estatísticas - PET");
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensPET/LogoPET.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 10, 120, 120);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Estatísticas");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 60, 150, 20);

        jLabel3.setText("Matéria:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 180, 80, 14);

        boxMesMateria.setMaximumRowCount(13);
        boxMesMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Stembro", "Outubro", "Novembro", "Dezembro" }));
        getContentPane().add(boxMesMateria);
        boxMesMateria.setBounds(160, 180, 70, 20);

        jLabel4.setText("Mês:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 160, 60, 14);

        jLabel5.setText("Ano:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 160, 50, 14);

        try {
            txtAnoMateria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtAnoMateria);
        txtAnoMateria.setBounds(280, 180, 50, 20);

        jLabel6.setText("Dia da Semana:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 240, 90, 14);

        jComboBox1.setMaximumRowCount(13);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(160, 240, 70, 20);

        jLabel7.setText("Mês:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 220, 60, 14);

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField2);
        jFormattedTextField2.setBounds(280, 240, 50, 20);

        jLabel8.setText("Ano:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 220, 50, 14);

        jLabel9.setText("Mês:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 300, 70, 14);

        try {
            txtAnoMes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtAnoMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoMesActionPerformed(evt);
            }
        });
        getContentPane().add(txtAnoMes);
        txtAnoMes.setBounds(280, 300, 50, 30);

        jLabel10.setText("Ano:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(280, 280, 50, 14);

        jButton1.setText("Tabela");
        getContentPane().add(jButton1);
        jButton1.setBounds(360, 180, 73, 23);

        jButton2.setText("Gráfico");
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 180, 70, 23);

        jButton3.setText("Tabela");
        getContentPane().add(jButton3);
        jButton3.setBounds(360, 240, 70, 23);

        jButton4.setText("Gráfico");
        getContentPane().add(jButton4);
        jButton4.setBounds(450, 240, 70, 23);

        btnEstatisticaMesTabela.setBackground(new java.awt.Color(0, 51, 255));
        btnEstatisticaMesTabela.setForeground(new java.awt.Color(255, 255, 255));
        btnEstatisticaMesTabela.setText("Tabela");
        btnEstatisticaMesTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstatisticaMesTabelaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstatisticaMesTabela);
        btnEstatisticaMesTabela.setBounds(360, 300, 70, 23);

        jButton6.setText("Gráfico");
        getContentPane().add(jButton6);
        jButton6.setBounds(450, 300, 70, 23);

        setSize(new java.awt.Dimension(714, 389));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnoMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoMesActionPerformed
        
    }//GEN-LAST:event_txtAnoMesActionPerformed

    private void btnEstatisticaMesTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstatisticaMesTabelaActionPerformed
        TelaTabelaEstMes telaE = new TelaTabelaEstMes(txtAnoMes.getText());
        //jDesktopPane.add(telaBuscaEst);
        telaE.setVisible(true);
    }//GEN-LAST:event_btnEstatisticaMesTabelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBuscaEstatisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxMesMateria;
    private javax.swing.JButton btnEstatisticaMesTabela;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField txtAnoMateria;
    private javax.swing.JFormattedTextField txtAnoMes;
    // End of variables declaration//GEN-END:variables
}
