package Interface;

import javax.swing.table.DefaultTableModel;
import model.bean.Dados;
import model.dao.PetDAO;
import Interface.TelaTabelaDados;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class TelaNovaMonitoria extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaNovaMonitoria1
     */
    public TelaNovaMonitoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNomeMonitor = new javax.swing.JTextField();
        txtNomeSegMonitor = new javax.swing.JTextField();
        txtLocal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnSalvarDados = new javax.swing.JButton();
        txtData = new javax.swing.JFormattedTextField();
        txtHora = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNomeAluno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCursoAluno = new javax.swing.JTextField();
        txtMateria = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtRA = new javax.swing.JFormattedTextField();

        setClosable(true);

        jScrollPane1.setBackground(new java.awt.Color(244, 244, 244));
        jScrollPane1.setRequestFocusEnabled(false);

        jPanel2.setBackground(new java.awt.Color(247, 247, 247));
        jPanel2.setForeground(new java.awt.Color(0, 51, 255));
        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nova Monitoria");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(120, 120, 175, 32);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nome do Segundo Monitor:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(32, 220, 150, 16);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome do Monitor:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(32, 164, 97, 16);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Hora:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(70, 430, 40, 16);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Data:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(230, 430, 29, 16);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Local:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(180, 380, 33, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensPET/LogoPET.jpg"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(150, 10, 118, 114);

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("RA Aluno:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 380, 53, 16);

        txtNomeMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeMonitorActionPerformed(evt);
            }
        });
        jPanel2.add(txtNomeMonitor);
        txtNomeMonitor.setBounds(32, 186, 340, 28);
        jPanel2.add(txtNomeSegMonitor);
        txtNomeSegMonitor.setBounds(32, 242, 340, 28);
        jPanel2.add(txtLocal);
        txtLocal.setBounds(180, 400, 190, 28);

        jLabel14.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Ano - Mês - Dia");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(230, 480, 72, 14);

        btnSalvarDados.setBackground(new java.awt.Color(0, 0, 204));
        btnSalvarDados.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarDados.setText("Salvar");
        btnSalvarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarDadosActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalvarDados);
        btnSalvarDados.setBounds(300, 500, 69, 28);

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtData);
        txtData.setBounds(230, 450, 80, 28);

        try {
            txtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtHora);
        txtHora.setBounds(70, 450, 50, 28);

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nome do Aluno:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(32, 276, 88, 16);

        txtNomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAlunoActionPerformed(evt);
            }
        });
        jPanel2.add(txtNomeAluno);
        txtNomeAluno.setBounds(32, 298, 340, 28);

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Curso do Aluno:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(32, 332, 88, 16);
        jPanel2.add(txtCursoAluno);
        txtCursoAluno.setBounds(30, 350, 190, 28);
        jPanel2.add(txtMateria);
        txtMateria.setBounds(240, 350, 130, 28);

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Matéria:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(240, 330, 43, 16);

        try {
            txtRA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtRA);
        txtRA.setBounds(30, 400, 127, 28);

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAlunoActionPerformed

    private void txtNomeMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeMonitorActionPerformed

    private void btnSalvarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarDadosActionPerformed
        //DefaultTableModel dtmDados = (DefaultTableModel) btnSalvarDados.getModel();
        //Object[] dadosLidos = {txtNomeMonitor.getText(), txtNomeSegMonitor.getText(), txtNomeAluno.getText(), txtCursoAluno.getText(), txtMateria.getText() ,txtRA.getText(), txtLocal.getText(), txtHora.getText(), txtData.getText()};
        //dtmDados.addRow(dadosLidos);
        
        
        if(txtNomeMonitor.getText().isEmpty() || txtMateria.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Erro: Campo obrigatório não preenchido \nCampos Obrigatórios: Nome do Monitor; Matéria");
        }else{
            Dados d = new Dados();
            PetDAO dao = new PetDAO();
            
            d.setNomeMonitor1(txtNomeMonitor.getText());
            d.setNomeMonitor2(txtNomeSegMonitor.getText());
            d.setNomeAluno(txtNomeAluno.getText());
            d.setCursoAluno(txtCursoAluno.getText());
            d.setMateriaAluno(txtMateria.getText());
            d.setRaAluno(Integer.parseInt(txtRA.getText()));
            d.setLocalMonitoria(txtLocal.getText());
            d.setHoraMonitoria(txtHora.getText());
            d.setDataMonitoria(txtData.getText());
        
            dao.create(d);
        
            txtNomeMonitor.setText("");
            txtNomeSegMonitor.setText("");
            txtNomeAluno.setText("");
            txtCursoAluno.setText("");
            txtMateria.setText("");
            txtRA.setText("");
            txtLocal.setText("");
            txtHora.setText("");
            txtData.setText("");
        }
        
        
        
        //readTabelaDados();
    }//GEN-LAST:event_btnSalvarDadosActionPerformed

    
//    public void readTabelaDados (){
//        DefaultTableModel dtmDados = (DefaultTableModel) btnSalvarDados.getModel();
//        
//        PetDAO pdao =  new PetDAO();
//        
//        for (Dados d: pdao.read()){
//            
//            dtmDados.addRow(new Object[]{
//                
//            });
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarDados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCursoAluno;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JFormattedTextField txtHora;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtMateria;
    private javax.swing.JTextField txtNomeAluno;
    private javax.swing.JTextField txtNomeMonitor;
    private javax.swing.JTextField txtNomeSegMonitor;
    private javax.swing.JFormattedTextField txtRA;
    // End of variables declaration//GEN-END:variables
}
