package Interface;

import javax.swing.table.DefaultTableModel;
import model.bean.Dados;
import model.dao.PetDAO;
import Interface.TelaTabelaEstMes;
import java.util.ArrayList;
import java.util.List;
import model.bean.EstatisticaMes;

/**
 * @author Lucas Vieira
 */
public class TelaTabelaEstMes extends javax.swing.JFrame {

    /**
     * Creates new form TelaTabelaEstatisticas
     */
    
    private String DataText;
    
    private Object btnEstatisticaMesTabela;
    
    
    
    public TelaTabelaEstMes() {
        initComponents();
    }
    
    public TelaTabelaEstMes(String DataText){
        initComponents();
        mostrarEstatisticasTMes(DataText);
    }
    
    public void mostrarEstatisticasTMes(String DataText){
        Dados dado = new Dados();
        PetDAO pdao =  new PetDAO();
        List<Dados> listaDados = new ArrayList<>();
        
        listaDados = pdao.searchData(DataText);
        
        String sAux;
        sAux = listaDados.get(0).getDataMonitoria();
        String[] dataB = sAux.split("-");
        EstatisticaMes m = new EstatisticaMes(dataB[0]);
        m.setTotal(listaDados.size());
        
        
        for (int i=0; i<listaDados.size(); i++){
            sAux = listaDados.get(i).getDataMonitoria();
            String[] dataC = sAux.split("-");
            switch (Integer.parseInt(dataC[1])) {
                case 1:
                    m.setJaneiro(m.getJaneiro()+1);
                    break;
                case 2:
                    m.setFevereiro(m.getFevereiro()+1);
                    break;
                case 3:
                    m.setMarco(m.getMarco()+1);
                    break;
                case 4:
                    m.setAbril(m.getAbril()+1);
                    break;
                case 5:
                    m.setMaio(m.getMaio()+1);
                    break;
                case 6:
                    m.setJunho(m.getJunho()+1);
                    break;
                case 7:
                    m.setJulho(m.getJulho()+1);
                    break;
                case 8:
                    m.setAgosto(m.getAgosto()+1);
                    break;
                case 9:
                    m.setSetembro(m.getSetembro()+1);
                    break;
                case 10:
                    m.setOutubro(m.getOutubro()+1);
                    break;
                case 11:
                    m.setNovembro(m.getNovembro()+1);
                    break;
                case 12:
                    m.setDezembro(m.getDezembro()+1);
                    break;
                default:
                    break;
            }
            
        }
        double mt, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12;
        mt = m.getTotal();
        m1 = m.getJaneiro();
        m2 = m.getFevereiro();
        m3 = m.getMarco();
        m4 = m.getAbril();
        m5 = m.getMaio();
        m6 = m.getJunho();
        m7 = m.getJulho();
        m8 = m.getAgosto();
        m9 = m.getSetembro();
        m10 = m.getOutubro(); 
        m11 = m.getNovembro();
        m12 = m.getDezembro();
        
        
        DefaultTableModel dtmDados = (DefaultTableModel) jTable2.getModel();
        dtmDados.setNumRows(0);
        for (int i=0; i<1; i++){
        dtmDados.addRow(new Object[]{
                m.getAno(),
                (m1/mt)*100,
                (m2/mt)*100,
                (m3/mt)*100,
                (m4/mt)*100,
                (m5/mt)*100,
                (m6/mt)*100,
                (m7/mt)*100,
                (m8/mt)*100,
                (m9/mt)*100,
                (m10/mt)*100,
                (m11/mt)*100,
                (m12/mt)*100
            });
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estatísticas - PET");
        setBackground(new java.awt.Color(237, 237, 237));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensPET/LogoPET.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 20, 120, 130);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Estatísticas");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 60, 240, 50);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ano", "Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dec"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 630, 120);

        jLabel3.setText("Obs: Valores em %");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 280, 170, 15);

        setBounds(0, 0, 654, 378);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTabelaEstMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTabelaEstMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTabelaEstMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTabelaEstMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTabelaEstMes().setVisible(true);
            }
        });
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
