/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Lucas
 */
public class TelaBuscaEstatisticas extends javax.swing.JFrame {

    /**
     * Creates new form TelaBuscaEstatisticas
     */
    public TelaBuscaEstatisticas() {
        initComponents();
        
        jComboBoxMes.setEnabled(false);
        txtAnoMes.setEnabled(false);
        btnGrafico.setEnabled(false);
        btnTabela.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAnoMes = new javax.swing.JFormattedTextField();
        btnTabela = new javax.swing.JButton();
        jRadioButtonMateria = new javax.swing.JRadioButton();
        jRadioButtonDSemana = new javax.swing.JRadioButton();
        jRadioButtonMes = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGrafico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estatísticas - PET");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Estatísticas");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 60, 150, 20);

        try {
            txtAnoMes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtAnoMes.setEnabled(false);
        txtAnoMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoMesActionPerformed(evt);
            }
        });
        jPanel1.add(txtAnoMes);
        txtAnoMes.setBounds(330, 160, 50, 30);

        btnTabela.setBackground(new java.awt.Color(0, 51, 255));
        btnTabela.setForeground(new java.awt.Color(255, 255, 255));
        btnTabela.setText("Tabela");
        btnTabela.setEnabled(false);
        btnTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabelaActionPerformed(evt);
            }
        });
        jPanel1.add(btnTabela);
        btnTabela.setBounds(410, 160, 70, 30);

        jRadioButtonMateria.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonMateria);
        jRadioButtonMateria.setText("Matéria");
        jRadioButtonMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMateriaActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonMateria);
        jRadioButtonMateria.setBounds(70, 160, 100, 23);

        jRadioButtonDSemana.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonDSemana);
        jRadioButtonDSemana.setText("Dia da Semana");
        jRadioButtonDSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDSemanaActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonDSemana);
        jRadioButtonDSemana.setBounds(70, 190, 120, 23);

        jRadioButtonMes.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonMes);
        jRadioButtonMes.setText("Mês");
        jRadioButtonMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMesActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonMes);
        jRadioButtonMes.setBounds(70, 220, 100, 23);

        jLabel1.setText("Buscar por:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 140, 80, 14);

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Janeiro", "Feveiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBoxMes.setEnabled(false);
        jPanel1.add(jComboBoxMes);
        jComboBoxMes.setBounds(210, 160, 90, 30);

        jLabel3.setText("Mês:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 140, 90, 14);

        jLabel4.setText("Ano:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(330, 140, 50, 14);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensPET/LogoPET2.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 20, 110, 100);

        btnGrafico.setBackground(new java.awt.Color(0, 51, 255));
        btnGrafico.setForeground(new java.awt.Color(255, 255, 255));
        btnGrafico.setText("Gráfico");
        btnGrafico.setEnabled(false);
        jPanel1.add(btnGrafico);
        btnGrafico.setBounds(500, 160, 67, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 640, 290);

        setSize(new java.awt.Dimension(646, 328));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnoMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoMesActionPerformed
        
    }//GEN-LAST:event_txtAnoMesActionPerformed

    private void btnTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabelaActionPerformed
        TelaEstMesTabela telaE = new TelaEstMesTabela(txtAnoMes.getText());
        //TelaTabelaEstMes telaE = new TelaTabelaEstMes(txtAnoMes.getText());
        telaE.setVisible(true);
    }//GEN-LAST:event_btnTabelaActionPerformed

    private void jRadioButtonMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMesActionPerformed
        if(jRadioButtonMes.isSelected()){
            jComboBoxMes.setEnabled(false);
            txtAnoMes.setEnabled(true);
            btnGrafico.setEnabled(true);
            btnTabela.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonMesActionPerformed

    private void jRadioButtonDSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDSemanaActionPerformed
        if(jRadioButtonDSemana.isSelected()){
            jComboBoxMes.setEnabled(true);
            txtAnoMes.setEnabled(true);
            btnGrafico.setEnabled(true);
            btnTabela.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonDSemanaActionPerformed

    private void jRadioButtonMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMateriaActionPerformed
        if(jRadioButtonMateria.isSelected()){
            jComboBoxMes.setEnabled(true);
            txtAnoMes.setEnabled(true);
            btnGrafico.setEnabled(true);
            btnTabela.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBuscaEstatisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrafico;
    private javax.swing.JButton btnTabela;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonDSemana;
    private javax.swing.JRadioButton jRadioButtonMateria;
    private javax.swing.JRadioButton jRadioButtonMes;
    private javax.swing.JFormattedTextField txtAnoMes;
    // End of variables declaration//GEN-END:variables
}
